# Generated by Django 5.2.17 on 2026-08-27 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=150)),
                ('lang', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], max_length=2)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'content_translations',
                'ordering': ['key', 'lang'],
                'constraints': [models.UniqueConstraint(fields=('key', 'lang'), name='unique_key_lang')],
            },
        ),
    ]
