services:
  - type: web
    name: ashrapov-rent-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ashrapov-rent-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: ashrapov-rent-db
    plan: free
