# Generated by Django 5.2.17 on 2026-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreement_video',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/videos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='worker_documents/id_cards/'),
        ),
    ]
