# Generated by Django 5.2.17 on 2026-08-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_worker_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='worker_documents/id_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='worker_documents/id_cards/'),
        ),
    ]
