# Generated by Django 5.2.17 on 2026-08-27 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electro_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('passport_photo', 'Passport rasmi'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='rental_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rental_media',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('period_days', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Faol'), ('overdue', "Muddati o'tgan"), ('completed', 'Yakunlangan')], default='active', max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='electro_units.electrounit')),
            ],
            options={
                'db_table': 'rentals',
                'ordering': ['-start_date'],
            },
        ),
    ]
