# Generated by Django 5.2.17 on 2026-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='pay_timing',
            field=models.CharField(choices=[('start', 'Boshida'), ('end', 'Oxirida')], default='start', max_length=10),
        ),
    ]
