# Generated by Django 5.2.17 on 2026-09-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_pay_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='battery_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ta batareya'), (2, '2 ta batareya')], null=True),
        ),
    ]
