# Generated by Django 5.2.17 on 2026-09-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('electro_units', '0003_add_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerapplication',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='electro_units.electrounit'),
        ),
    ]
