# Generated by Django 5.2.17 on 2026-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_add_unit_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerapplication',
            name='pay_timing',
            field=models.CharField(choices=[('start', 'Boshida'), ('end', 'Oxirida')], default='start', max_length=10),
        ),
        migrations.AddField(
            model_name='workerapplication',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik')], default='weekly', max_length=10),
        ),
    ]
