# Generated by Django 5.2.17 on 2026-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_workerapplication_pay_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerapplication',
            name='battery_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ta batareya'), (2, '2 ta batareya')], help_text='Faqat skuter uchun: 1 yoki 2 batareya', null=True),
        ),
    ]
