# Generated by Django 5.2.17 on 2026-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='ai_extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='ai_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='ai_verdict',
            field=models.CharField(blank=True, choices=[('real', 'Haqiqiy chek'), ('fake', 'Shubhali'), ('unclear', 'Aniqlanmadi')], max_length=10, null=True),
        ),
    ]
