# Generated by Django 5.2.17 on 2026-09-07 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_ai_receipt_fields'),
        ('rentals', '0003_rental_pay_timing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='ai_extracted_amount',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='ai_raw_text',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='ai_verdict',
        ),
        migrations.AddField(
            model_name='payment',
            name='covered_days',
            field=models.PositiveIntegerField(blank=True, help_text="Bu to'lov ijara muddatini necha kunga uzaytirgani.", null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('receipt', 'Chek orqali')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_fines', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['rental', 'is_fine', 'paid_at'], name='pay_rental_kind_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='pay_paid_at_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['status', '-uploaded_at'], name='receipt_status_time_idx'),
        ),
    ]
