# Generated by Django 5.2.17 on 2026-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='covered_days',
            field=models.IntegerField(blank=True, help_text="Bu to'lov ijara muddatini necha kunga o'zgartirgani.", null=True),
        ),
    ]
