# Generated by Django 5.2.17 on 2026-08-27 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('available', "Bo'sh"), ('rented', 'Band'), ('maintenance', "Ta'mirlashda")], default='available', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='electro_units/')),
            ],
            options={
                'db_table': 'electro_units',
                'ordering': ['model_name'],
            },
        ),
    ]
