# Generated by Django 5.2.17 on 2026-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrounit',
            name='unit_type',
            field=models.CharField(choices=[('scooter', 'Skuter'), ('bike', 'Velik')], default='scooter', max_length=20),
        ),
    ]
