# Generated by Django 5.2.17 on 2026-09-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_units', '0002_electrounit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrounit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
